blog_app/urls.py
from django.conf.urls import url
from django.urls import path
from blog_app import views

app_name = "blog_app"

urlpatterns = [
    path('', views.blog, name='blog'),

]

fashion_app/urls.py
from django.conf.urls import url
from django.urls import path
from fashion_app import views

app_name = "fashion_app"

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.customerlogin, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),

]

fashion_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('fashion_app.urls')),
    path('', include('store_app.urls')),
    path('order/', include('order_app.urls')),
    path('payment/', include('payment_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('about/', include('about_app.urls')),
    path('contact/', include('contact_app.urls')),

]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

fashion_app/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils.translation import ugettext_lazy
from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password
# Create your models here.



class MyUserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError("The Email must be set!")

        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser Must have is_staff=True')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True')            
        return  self._create_user(email, password, **extra_fields)


class User (AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True, null=False)
    is_staff = models.BooleanField(
        ugettext_lazy('staff status'),
        default=False,
        help_text=ugettext_lazy('Designates whether the user can log in this site')
    )

    is_active = models.BooleanField(
        ugettext_lazy('active'),
        default=True,
        help_text = ugettext_lazy('Designates whether this user should be treated as active. Unselect this instead of deleting accounts')
    )

    USERNAME_FIELD = 'email'
    objects = MyUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.email

    def get_short_name(self):
        return self.email



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    full_name = models.CharField(max_length=100, blank=True, null=True)
    address = models.TextField(max_length=300, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    zipcode = models.CharField(max_length=20, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    date_joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user}'s profile"

@receiver(post_save, sender = User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()

fashion_app/forms.py
from dataclasses import fields
from pyexpat import model
from django.forms import ModelForm
# from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from fashion_app.models import Profile, User


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('__all__')
        exclude = ('user',)


class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')

fashion_app/views.py
from multiprocessing import context
from django.shortcuts import redirect, render, HttpResponseRedirect
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy

from fashion_app.forms import ProfileForm, RegistrationForm

# Authentication function
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import AuthenticationForm

from order_app.models import Cart, Order
from payment_app.models import BillingAddress
from payment_app.forms import BillingAddressForm
from fashion_app.models import Profile

from django.views.generic import TemplateView

#messages
from django.contrib import messages

# Create your views here.

def register(request):
    if request.user.is_authenticated:
        return HttpResponse('You are authenticate')
    else:
        form = RegistrationForm()
        if request.method == 'POST':
            form = RegistrationForm(request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, "Account Create Successfully!")
                return HttpResponseRedirect(reverse('fashion_app:login'))
    context = {'form': form}
    return render(request, 'fashion_app/register.html', context)


def customerlogin(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('store_app:index'))
    context = {
        'form': form
    }
    return render(request, 'fashion_app/login.html', context)



@login_required
def logout_user(request):
    logout(request)
    messages.warning(request, "Logged Out Successfully!")
    return HttpResponseRedirect(reverse('store_app:index'))



class ProfileView(TemplateView):
    def get(self, request, *args, **kwargs):
        orders = Order.objects.filter(user=request.user, ordered = True)

        billingaddress = BillingAddress.objects.get(user=request.user)

        billingaddress_form = BillingAddressForm(instance=billingaddress)

        profile_obj = Profile.objects.get(user=request.user)
        profileForm = ProfileForm(instance=profile_obj)
        context = {
            'orders' : orders,
            'billingaddress' : billingaddress_form,
            'profileForm' : profileForm,
        }
        
        return render(request, 'fashion_app/profile.html', context)


    def post(self, request, *args, **kwargs):
        if request.method == 'post' or request.method == 'POST':
            billingaddress = BillingAddress.objects.get(user=request.user)
            billingaddress_form = BillingAddressForm(request.POST, instance=billingaddress)

            profile_obj = Profile.objects.get(user=request.user)
            profileForm = ProfileForm(request.POST, instance=profile_obj)
            if billingaddress_form.is_valid() or profileForm.is_valid():
                billingaddress_form.save()
                profileForm.save()
                return redirect('fashion_app:profile')

templates/fashion_app/login.html
{% extends 'base.html' %}
{% block title %} AjkerOrder | Login {% endblock title %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block body %}


<body>
    <div style="padding: 50px;">
        <form action="" method="POST">
            {{ form | crispy }}
            {% csrf_token %}
            <button type="submit" class="btn btn-primary btn-sm">Login</button>
        </form>
        <br>
        <p>Doesn't Have an account? <a href="{% url 'fashion_app:register' %}">Create New Account</a></p>
    </div>
</body>


{% endblock %}

templates/fashion_app/profile.html
{% extends 'base.html' %}
{% block title %} AjkerOrder | Profile {% endblock title %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block body %}

        <main class="main">
        	<div class="page-header text-center" style="background-image: url('assets/images/page-header-bg.jpg')">
        		<div class="container">
        			<h1 class="page-title">My Account<span>{{ user.email }}</span></h1>
        		</div><!-- End .container -->
        	</div><!-- End .page-header -->
			
            <nav aria-label="breadcrumb" class="breadcrumb-nav mb-3">
            </nav><!-- End .breadcrumb-nav -->

            <div class="page-content">
            	<div class="dashboard">
	                <div class="container">
	                	<div class="row">
	                		<aside class="col-md-4 col-lg-3">
	                			<ul class="nav nav-dashboard flex-column mb-3 mb-md-0" role="tablist">
								    <li class="nav-item">
								        <a class="nav-link" id="tab-orders-link" data-toggle="tab" href="#tab-orders" role="tab" aria-controls="tab-orders" aria-selected="false">Orders</a>
								    </li>

									<li class="nav-item">
								        <a class="nav-link" id="tab-account-link" data-toggle="tab" href="#tab-account" role="tab" aria-controls="tab-account" aria-selected="false">Account Details</a>
								    </li>
								    
								    <li class="nav-item">
								        <a class="nav-link" id="tab-address-link" data-toggle="tab" href="#tab-address" role="tab" aria-controls="tab-address" aria-selected="false">Billing Adresses</a>
								    </li>
					
								    <li class="nav-item">
								        <a class="nav-link" href="{% url 'fashion_app:logout' %}">Sign Out</a>
								    </li>
								</ul>
	                		</aside><!-- End .col-lg-3 -->

	                		<div class="col-md-8 col-lg-9">
	                			<div class="tab-content">

								    <div class="tab-pane fade" id="tab-orders" role="tabpanel" aria-labelledby="tab-orders-link">
								    	
								    

										<table class="table table-bordered border-primary text-center">
											<thead>
											  <tr>
												<th scope="col"> Serial </th>
												<th scope="col">Products</th>
												<th scope="col">Payment ID</th>
												<th scope="col">Order ID</th>
											  </tr>
											</thead>
											<tbody>
												{% for order in orders %}
											  <tr>
												<th scope="row">{{ order.id }}</th>
												<td>
													{% for order_item in order.orderitems.all %}
													{{ order_item }}
													{% endfor %}
												</td>
												<td>{{ order.paymentId }}</td>
												<td>{{ order.orderId }}</td>
											  </tr>
											  {% endfor %}
											</tbody>
										  </table>





								    </div><!-- .End .tab-pane -->


								    <div class="tab-pane fade" id="tab-address" role="tabpanel" aria-labelledby="tab-address-link">
								    	<p>The following addresses will be used on the checkout page by default.</p>

								    	<div class="row">
								    		<div class="col-lg-12">
								    			<div class="card card-dashboard">
								    				<div class="card-body">
								    					<h3 class="card-title">Billing Address</h3><!-- End .card-title -->

														<form action="" method="POST">
															{% csrf_token %}

															{% comment %} {{ billingaddress }} {% endcomment %}


															{{ billingaddress.first_name|as_crispy_field }}
															{{ billingaddress.last_name|as_crispy_field }}
															{{ billingaddress.country|as_crispy_field }}
															{{ billingaddress.address1|as_crispy_field }}
															{{ billingaddress.address2|as_crispy_field }}
															{{ billingaddress.city|as_crispy_field }}
															{{ billingaddress.zipcode|as_crispy_field }}
															{{ billingaddress.phone_number|as_crispy_field }}
															
															<br>
															<input type="submit" value="Save Address">
														</form>
														
								    				</div><!-- End .card-body -->
								    			</div><!-- End .card-dashboard -->
								    		</div><!-- End .col-lg-6 -->

								    		{% comment %} <div class="col-lg-6">
								    			<div class="card card-dashboard">
								    				<div class="card-body">
								    					<h3 class="card-title">Shipping Address</h3><!-- End .card-title -->

														<p>You have not set up this type of address yet.<br>
														<a href="#">Edit <i class="icon-edit"></i></a></p>
								    				</div><!-- End .card-body -->
								    			</div><!-- End .card-dashboard -->
								    		</div><!-- End .col-lg-6 --> {% endcomment %}

								    	</div><!-- End .row -->
								    </div><!-- .End .tab-pane -->

								    <div class="tab-pane fade" id="tab-account" role="tabpanel" aria-labelledby="tab-account-link">
								    	<form action="" method='POST'>
			                				<div class="row">
			                					<div class="col-sm-12">
			                						{% csrf_token %}
													{% comment %} {{ profileForm.as_p }} {% endcomment %}

													{{ profileForm.full_name|as_crispy_field }}
													{{ profileForm.address|as_crispy_field }}
													{{ profileForm.country|as_crispy_field }}
													{{ profileForm.city|as_crispy_field }}
													{{ profileForm.zipcode|as_crispy_field }}
													{{ profileForm.phone|as_crispy_field }}

			                					</div><!-- End .col-sm-6 -->

			                				
			                				</div><!-- End .row -->

		            					

		                					<button type="submit" class="btn btn-outline-primary-2">
			                					<span>SAVE CHANGES</span>
			            						<i class="icon-long-arrow-right"></i>
			                				</button>
			                			</form>
								    </div><!-- .End .tab-pane -->
								</div>
	                		</div><!-- End .col-lg-9 -->
	                	</div><!-- End .row -->
	                </div><!-- End .container -->
                </div><!-- End .dashboard -->
            </div><!-- End .page-content -->
        </main><!-- End .main -->

{% endblock %}

templates/fashion_app/register.html
{% extends 'base.html' %}
{% block title %} AjkerOrder | Sign Up {% endblock title %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% block body %}

<body>
    <div style="padding: 50px;">
      <form action="" method="POST">
        {% csrf_token %}
        {{ form | crispy }}
        <button type="submit" class="btn btn-success btn-sm">Create Account</button>
    </form>
    <br>
    <p>Already Have an Account? <a href="{% url 'fashion_app:login' %}">Login Here</a></p>
    </div>
</body>

{% endblock %}