blog_app/urls.py
from django.conf.urls import url
from django.urls import path
from blog_app import views

app_name = "blog_app"

urlpatterns = [
    path('', views.blog, name='blog'),

]

fashion_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('fashion_app.urls')),
    path('', include('store_app.urls')),
    path('order/', include('order_app.urls')),
    path('payment/', include('payment_app.urls')),
    path('blog/', include('blog_app.urls')),
    path('about/', include('about_app.urls')),
    path('contact/', include('contact_app.urls')),

]


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

order_app/urls.py
from unicodedata import name
from django.urls import path
from order_app import views

app_name = "order_app"

urlpatterns = [
    path('add-to-cart/<int:pk>/',views.add_to_cart, name='add-to-cart'),
    path('buy_now/<int:pk>/',views.buy_now, name='buy_now'),
    path('cart-view/',views.cart_view, name='cart'),
    path('remove-item/<int:pk>/', views.remove_item_from_cart, name='remove-item'),
    path('increase-quantity/<int:pk>/', views.increase_cart, name='increase'),
    path('decrease-quantity/<int:pk>/', views.decrease_cart, name='decrease'),
]

store_app/urls.py
from django.conf.urls import url
from django.urls import path
from store_app import views

app_name = "store_app"

urlpatterns = [
    path('', views.HomeListView.as_view(), name='index'),
    path('product/<slug:slug>/', views.ProductDetailView.as_view(), name='product_details'),
    path('category/<slug:slug>/', views.category_details, name='category_details'),
    path('shop/', views.ShopListView.as_view(), name='shop'),

]

store_app/models.py
from email.mime import image
from itertools import product
from msilib.schema import Class
from pyexpat import model
from unicodedata import category, name
from webbrowser import get
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify
from django.contrib.auth import get_user_model

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=50,unique=True, blank=False, null=False)
    image = models.ImageField(upload_to='category', blank=False, null=False)
    parent = models.ForeignKey('self', related_name='children', on_delete=models.CASCADE, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-created',]
        verbose_name_plural = 'Categories'


    def get_category_url(self):
        return reverse('store_app:category_details', kwargs={'slug': self.slug})


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)


class Product(models.Model):
    name = models.CharField(max_length=250, blank=False, null=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    preview_description = models.CharField(max_length=255, verbose_name='Short Descriptions')
    description = models.TextField(max_length=1000, verbose_name='description')
    image = models.ImageField(upload_to  = 'products', blank=False, null = False)
    price = models.FloatField()
    old_price = models.FloatField(default=0.00, blank=True, null=True)
    is_stock = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    

    class Meta:
        ordering = ['-created']


    def get_product_url(self):
        return reverse('store_app:product_details', kwargs={'slug': self.slug})


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)



class ProductImages(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.FileField(upload_to='product_gallery')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.product.name)
    


class VariationManager(models.Manager):
    def sizes(self):
        return super(VariationManager, self).filter(variation='size')
    
    def colors(self):
        return super(VariationManager, self).filter(variation='color')


VARIATIONS_TYPE = (
    ('size','size'),
    ('color','color')
)

class VariationValue(models.Model):
    variation = models.CharField(max_length=100, choices=VARIATIONS_TYPE)
    name = models.CharField(max_length=100)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    price = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)

    objects = VariationManager()

    def __str__(self):
        return self.name
    

class Banner(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='banner')
    image = models.ImageField(upload_to = 'banner')
    is_active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name
    


User = get_user_model()

class MyLogo(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to = 'logo')
    is_active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.image)


class MyFavicon(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to = 'logo')
    is_active = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.image)
    

store_app/views.py
from itertools import product
from multiprocessing import context
from pyexpat import model
from re import search
from unicodedata import category, name
from django.shortcuts import render

from django.views.generic import ListView, DetailView, TemplateView
from store_app.models import Category, Product, ProductImages, Banner

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

# Create your views here.

# def home(request):
#     return render(request, 'store_app/index-4.html')


class HomeListView(TemplateView):
    def get(self, request, *args, **kwargs):

        products = Product.objects.all().order_by('-id')
        
        print(products)
        banners = Banner.objects.filter(is_active=True).order_by('-id')[0:5]
        categorys = Category.objects.all().order_by('-id')
        print("///////////////11111111111///////////////////")
        print(categorys)
        print("//////////////////////////////////")

        context = {
            'products' : products,
            'banners' : banners,
            'categorys' : categorys
        }
        return render(request, 'store_app/index-4.html', context)

    def post(self, request, *args, **kwargs):
        if request.method == 'post' or request.method == 'POST':
            search_product = request.POST.get('search_product')
            products = Product.objects.filter(name__icontains=search_product).order_by('-id')
            context = {
                'products' : products
                }
            return render(request, 'store_app/search.html', context)




class ShopListView(TemplateView):
    def get(self, request, *args, **kwargs):

        products = Product.objects.all().order_by('-id')
        paginator = Paginator(products,4)
        page = request.GET.get('page')

        print(products)
        banners = Banner.objects.filter(is_active=True).order_by('-id')[0:5]
        categorys = Category.objects.all().order_by('-id')
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)

        context = {
            'products' : products,
            'banners' : banners,
            'categorys' : categorys
        }
        return render(request, 'store_app/shop.html', context)

    def post(self, request, *args, **kwargs):
        if request.method == 'post' or request.method == 'POST':
            search_product = request.POST.get('search_product')
            products = Product.objects.filter(name__icontains=search_product).order_by('-id')
            context = {
                'products' : products
                }
            return render(request, 'store_app/search.html', context)





    # model = Product
    # template_name = 'store_app/index-4.html'
    # context_object_name = "products"

    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['banners'] = Banner.objects.filter(is_active=True).order_by('-id')[0:5]
    #     return context


# def product_details(request, pk):
#     item = Product.objects.get(id=pk)
#     context = {
#         'item': item
#     }
#     return render (request, 'store_app/product.html', context)


class ProductDetailView(DetailView):
    model = Product
    template_name = 'store_app/product.html'
    context_object_name = "item"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product_images'] = ProductImages.objects.filter(product=self.object.id)
        return context



    def post(self, request, *args, **kwargs):
        if request.method == 'post' or request.method == 'POST':
            search_product = request.POST.get('search_product')
            products = Product.objects.filter(name__icontains=search_product).order_by('-id')
            context = {
                'products' : products
                }
            return render(request, 'store_app/search.html', context)


# class CategorieDetailView(DetailView):
#     model = Category
#     template_name = 'store_app/category.html'
    
#     context_object_name = "category"

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         print(product)
#         return context



def category_details(request, slug):
    category = Category.objects.get(slug=slug)
    product = Product.objects.filter(category=category)





    if request.method == 'post' or request.method == 'POST':
        search_product = request.POST.get('search_product')
        products = Product.objects.filter(name__icontains=search_product).order_by('-id')
        context = {
            'products' : products
            }
        return render(request, 'store_app/search.html', context)





    print("/////////////////222222222222/////////////////")
    print(category)
    print("//////////////////////////////////")
    print(product)
    context = {
        'category': category,
        'product' : product
    }
    return render (request, 'store_app/category.html', context)

templates/store_app/category.html
{% extends 'base.html' %}
{% load category %}
{% block title %} AjkerOrder | Category {% endblock title %}
{% block body %}

        <main class="main">
        	<div class="page-header text-center" style="background-image: url('assets/images/page-header-bg.jpg')">
        		<div class="container">
        			<h1 class="page-title">Categories<span>Shop</span></h1>
        		</div><!-- End .container -->
        	</div><!-- End .page-header -->
            <nav aria-label="breadcrumb" class="breadcrumb-nav mb-2">
                <div class="container">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                    </ol>
                </div><!-- End .container -->
            </nav><!-- End .breadcrumb-nav -->

            <div class="page-content">
                <div class="container">
                    

                    <div class="products">
                        <div class="row">

                            
                            

                            {% if product %}
                            {% for all_product in product %}

                            <div class="col-6 col-md-4 col-lg-4 col-xl-3">
                                
                          
                                <div class="product">
                                    <figure class="product-media">
                                        
                                        <a href="{{ all_product.get_product_url }}">
                                            <img src="{{ all_product.image.url }}" alt="Product image" class="product-image">
                                        </a>

                                    </figure><!-- End .product-media -->

                                    <div class="product-body">
                                        <div class="product-cat">
                                            <a href="#">{{ category.name }}</a>
                                        </div><!-- End .product-cat -->
                                        
                                        <h3 class="product-title"><a href="{{ all_product.get_product_url }}">{{ all_product.name }}</a></h3><!-- End .product-title -->
                                        
                                        <div class="product-price">
                                            $ {{ all_product.price }}
                                        </div><!-- End .product-price -->

                                    </div><!-- End .product-body -->
                                </div><!-- End .product -->
                                
                                
                            </div><!-- End .col-sm-6 col-lg-4 col-xl-3 -->
                            {% endfor %}
                            {% else %}
                            <h3>Product Not Found</h3>
                            {% endif %}


                            
                            


                        </div><!-- End .row -->

                        <div class="load-more-container text-center">
                            <a href="{% url 'store_app:shop' %}" class="btn btn-outline-darker btn-load-more">More Products <i class="icon-refresh"></i></a>
                        </div><!-- End .load-more-container -->
                    </div><!-- End .products -->

                    <div class="sidebar-filter-overlay"></div><!-- End .sidebar-filter-overlay -->
                    

                </div><!-- End .container -->
            </div><!-- End .page-content -->
        </main><!-- End .main -->

        {% endblock %}

templates/store_app/pagination.html
<div class="">
    <span class="">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}

    <span class="">
    Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>

    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
</div>

templates/store_app/product.html
{% extends 'base.html' %}
{% block title %} AjkerOrder | Product {% endblock title %}
{% block body %}

<main class="main">
    <nav aria-label="breadcrumb" class="breadcrumb-nav border-0 mb-0">
        <div class="container d-flex align-items-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Products</a></li>
                <li class="breadcrumb-item active" aria-current="page">Default</li>
            </ol>

            {% comment %} <nav class="product-pager ml-auto" aria-label="Product">
                <a class="product-pager-link product-pager-prev" href="#" aria-label="Previous" tabindex="-1">
                    <i class="icon-angle-left"></i>
                    <span>Prev</span>
                </a>

                <a class="product-pager-link product-pager-next" href="#" aria-label="Next" tabindex="-1">
                    <span>Next</span>
                    <i class="icon-angle-right"></i>
                </a>
            </nav><!-- End .pager-nav --> {% endcomment %}

        </div><!-- End .container -->
    </nav><!-- End .breadcrumb-nav -->

    <div class="page-content">
        <div class="container">
            <div class="product-details-top">
                <div class="row">
                    <div class="col-md-6">
                        <div class="product-gallery product-gallery-vertical">
                            <div class="row">
                                <figure class="product-main-image">
                                    <img id="product-zoom" src="{{ item.image.url }}"
                                        data-zoom-image="assets/images/products/single/1-big.jpg" alt="product image">

                                    <a href="#" id="btn-product-gallery" class="btn-product-gallery">
                                        <i class="icon-arrows"></i>
                                    </a>
                                </figure><!-- End .product-main-image -->

                                <div id="product-zoom-gallery" class="product-image-gallery">
                                    {% for product_image in product_images %}
                                    <a class="product-gallery-item active" href="#"
                                        data-image="{{ product_image.image.url }}"
                                        data-zoom-image="{{ product_image.image.url }}">
                                        <img src="{{ product_image.image.url }}" alt="product side">
                                    </a>
                                    {% endfor %}
                                </div><!-- End .product-image-gallery -->
                            </div><!-- End .row -->
                        </div><!-- End .product-gallery -->
                    </div><!-- End .col-md-6 -->

                    <div class="col-md-6">
                        <div class="product-details">
                            <h1 class="product-title">{{ item.name }}</h1><!-- End .product-title -->

                            {% comment %} <div class="ratings-container">
                                <div class="ratings">
                                    <div class="ratings-val" style="width: 80%;"></div><!-- End .ratings-val -->
                                </div><!-- End .ratings -->
                                <a class="ratings-text" href="#product-review-link" id="review-link">( 2 Reviews )</a>
                            </div><!-- End .rating-container --> {% endcomment %}



                            <div class="product-details-footer">

                                <div class="product-cat">
                                    <span>Category:</span>
                                    <a href="#">{{ item.category }}</a>,
                                </div><!-- End .product-cat -->

                            </div><!-- End .product-details-footer -->


                            <div class="product-price">
                                ৳ {{ item.price }}
                            </div><!-- End .product-price -->
                            {% if item.old_price %}
                            <div class="product-price">
                                <del>৳ {{ item.old_price }}</del>
                            </div><!-- End .product-price -->
                            {% endif %}

                            <div class="product-content">
                                <p>{{ item.preview_description }}</p>
                            </div><!-- End .product-content -->






                            <form method="POST" action="{% url 'order_app:add-to-cart' pk=item.pk %}">
                                {% csrf_token %}
                                {% if item.variationvalue_set.colors %}
                                <div class="details-filter-row details-row-size">
                                    <label for="size">Color:</label>
                                    <div class="select-custom">
                                        <select name="color" id="size" class="form-control">
                                            <option value="#" selected="selected">Select a color</option>
                                            {% for item_variation in item.variationvalue_set.colors %}
                                            <option value="{{ item_variation.name }}">{{ item_variation.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div><!-- End .select-custom -->
                                </div><!-- End .details-filter-row -->
                                {% endif %}




                                {% if item.variationvalue_set.sizes %}
                                <div class="details-filter-row details-row-size">
                                    <label for="size">Size:</label>
                                    <div class="select-custom">
                                        <select name="size" id="size" class="form-control">
                                            <option value="#" selected="selected">Select a size</option>
                                            {% for item_variation in item.variationvalue_set.sizes %}
                                            <option value="{{ item_variation.name }}">{{ item_variation.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div><!-- End .select-custom -->
                                </div><!-- End .details-filter-row -->
                                {% endif %}


                                {% comment %} <div class="details-filter-row details-row-size">
                                    <label for="qty">Qty:</label>
                                    <div class="product-details-quantity">
                                        <input type="number" id="qty" class="form-control" value="1" min="1" max="10"
                                            step="1" data-decimals="0" required>
                                    </div><!-- End .product-details-quantity -->
                                </div><!-- End .details-filter-row --> {% endcomment %}


                                <div class="product-details-footer">

                                </div><!-- End .product-details-footer -->


                                <div class="product-details-action">

                                    <button type="submit" class="btn-product btn-cart">Add to Cart</button>

                                </div><!-- End .product-details-action -->


                                {% comment %} <div class="product-details-action">
                                    <a href="{% url 'order_app:cart' %}"><button type="submit" class="btn-product btn-cart"> Buy Now</button></a>
                                </div><!-- End .product-details-action --> {% endcomment %}


                            </form>











                            <form method="POST" action="{% url 'order_app:buy_now' pk=item.pk %}">
                                {% csrf_token %}
                                {% if item.variationvalue_set.colors %}
                                <div class="details-filter-row details-row-size">
                                    <label for="size">Color:</label>
                                    <div class="select-custom">
                                        <select name="color" id="size" class="form-control">
                                            <option value="#" selected="selected">Select a color</option>
                                            {% for item_variation in item.variationvalue_set.colors %}
                                            <option value="{{ item_variation.name }}">{{ item_variation.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div><!-- End .select-custom -->
                                </div><!-- End .details-filter-row -->
                                {% endif %}




                                {% if item.variationvalue_set.sizes %}
                                <div class="details-filter-row details-row-size">
                                    <label for="size">Size:</label>
                                    <div class="select-custom">
                                        <select name="size" id="size" class="form-control">
                                            <option value="#" selected="selected">Select a size</option>
                                            {% for item_variation in item.variationvalue_set.sizes %}
                                            <option value="{{ item_variation.name }}">{{ item_variation.name }}</option>
                                            {% endfor %}
                                        </select>
                                    </div><!-- End .select-custom -->
                                </div><!-- End .details-filter-row -->
                                {% endif %}


                                {% comment %} <div class="details-filter-row details-row-size">
                                    <label for="qty">Qty:</label>
                                    <div class="product-details-quantity">
                                        <input type="number" id="qty" class="form-control" value="1" min="1" max="10"
                                            step="1" data-decimals="0" required>
                                    </div><!-- End .product-details-quantity -->
                                </div><!-- End .details-filter-row --> {% endcomment %}


                                <div class="product-details-footer">

                                </div><!-- End .product-details-footer -->


                                <div class="product-details-action">

                                    <button type="submit" class="btn-product btn-cart">Buy Now</button>

                                </div><!-- End .product-details-action -->


                            </form>













                        </div><!-- End .product-details -->
                    </div><!-- End .col-md-6 -->
                </div><!-- End .row -->
            </div><!-- End .product-details-top -->

            <div class="product-details-tab">
                <ul class="nav nav-pills justify-content-center" role="tablist">
                    <li class="nav-item">
                        <a class="nav-link active" id="product-desc-link" data-toggle="tab" href="#product-desc-tab"
                            role="tab" aria-controls="product-desc-tab" aria-selected="true">Description</a>
                    </li>

                </ul>
                <div class="tab-content">
                    <div class="tab-pane fade show active" id="product-desc-tab" role="tabpanel"
                        aria-labelledby="product-desc-link">
                        <div class="product-desc-content">


                            {{ item.description }}


                        </div><!-- End .product-desc-content -->
                    </div><!-- .End .tab-pane -->


                </div><!-- End .tab-content -->
            </div><!-- End .product-details-tab -->


            <div style="margin-left: 25%; margin-right: 25%;">
                <a href="{% url 'store_app:shop' %}" class="btn btn-outline-dark-2 btn-block mb-3"><span>CONTINUE
                        SHOPPING</span><i class="icon-refresh"></i></a>
            </div>



        </div><!-- End .container -->
    </div><!-- End .page-content -->
</main><!-- End .main -->

{% endblock %}

templates/store_app/status.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    <title>Payment Status</title>
</head>
<body>
    <div class="container">
      <div class="messages container mt-2">
        {% if messages %}
        {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{message.tags}} {% endif %}" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                    aria-hidden="true">&times;</span></button>
        </div>
        {% endfor %}
        {% endif %}
    </div>
    </div>
</body>
</html>